apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: demo-scaffolder-backend-module-git
  title: Demo the Scaffolder Backend Module with Git
  description: scaffolder git template demo
spec:
  owner: backstage/scaffolder-backend
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - repositoryUrl
        - branchName
      properties:
        repositoryUrl:
          title: Repository Url
          type: string
          description: The remote repository URL. If the access is private, be sure to configure your integrations configuration.
        branchName:
          title: Branch Name
          type: string
          description: The name of the branch to checkout.
        shouldCreate:
          title: shouldCreate
          type: boolean
          description: If the branch doesn't exist and we need to create it before checking out.

  steps:
    - id: clone
      name: Clone the repository
      action: git:clone
      input:
        repositoryUrl: '${{ parameters.repositoryUrl }}'
        # repositoryConfig: # optional, will default to user info associated with the token if available
        #   userName: ''
        #   email: ''
        # workingDirectory: '.' # optional, relative to the scaffolder workspace path

    - id: checkout
      name: Checkout the branch
      action: git:checkout
      input:
        branchName: '${{ parameters.branchName }}'
        shouldCreate: '${{ parameters.shouldCreate }}'
        # strategy: 'safe' # optional
        # workingDirectory: '.' # optional, relative to the scaffolder workspace path

    - id: changes
      name: Make some changes
      action: fetch:plain
      input:
        url: ./templates/DEMO.md
        targetPath: './DEMO.md'

    - id: add
      name: Add changes to the index
      action: git:add
      # input:
      #   files: []
      #   workingDirectory: '.' # optional, relative to the scaffolder workspace path

    - id: commit
      name: Commit changes
      action: git:commit
      input:
        message: 'demo: test commit action in demo template'
        # author:
        #   name: ''
        #   email: ''
        # committer:
        #   name: ''
        #   email: ''

    - id: push
      name: Push changes to the remote repository
      action: git:push
      # input:
      #   remote: ''
      #   branch: ''
      #   workingDirectory: '.' # optional, relative to the scaffolder workspace path

  output:
    text:
      - title: Output
        content: |
          ### Default branch head commit
          **sha**: ${{ steps['clone'].output.head.sha }}  
          **author.name**: ${{ steps['clone'].output.head.author.name }}  
          **author.email**: ${{ steps['clone'].output.head.author.email }}  
          **committer.name**: ${{ steps['clone'].output.head.committer.name }}  
          **committer.email**: ${{ steps['clone'].output.head.committer.email }}  
          **date**: ${{ steps['clone'].output.head.date }}  
          **message**: ${{ steps['clone'].output.head.message }}  
          ### Branch head commit
          **sha**: ${{ steps['commit'].output.head.sha }}  
          **author.name**: ${{ steps['commit'].output.head.author.name }}  
          **author.email**: ${{ steps['commit'].output.head.author.email }}  
          **committer.name**: ${{ steps['commit'].output.head.committer.name }}  
          **committer.email**: ${{ steps['commit'].output.head.committer.email }}  
          **date**: ${{ steps['commit'].output.head.date }}  
          **message**: ${{ steps['commit'].output.head.message }}
